### ISSUE TITLE
WordCount using Flink not working

### ISSUE THREAD

**Issue by zkaoudi** [apache/incubator-wayang#420]
I tried to run the Wordcount with Flink and got this error:

Exception in thread "main" org.apache.wayang.core.api.exception.WayangException: Executing T[FlinkReduceBy[Add counters]] failed.
	at org.apache.wayang.flink.execution.FlinkExecutor.execute(FlinkExecutor.java:113)
	at org.apache.wayang.core.platform.PushExecutorTemplate.execute(PushExecutorTemplate.java:73)
	at org.apache.wayang.core.platform.PushExecutorTemplate$StageExecution.execute(PushExecutorTemplate.java:195)
	at org.apache.wayang.core.platform.PushExecutorTemplate$StageExecution.doExecute(PushExecutorTemplate.java:166)
	at org.apache.wayang.core.util.OneTimeExecutable.tryExecute(OneTimeExecutable.java:41)
	at org.apache.wayang.core.util.OneTimeExecutable.execute(OneTimeExecutable.java:54)
	at org.apache.wayang.core.platform.PushExecutorTemplate$StageExecution.executeStage(PushExecutorTemplate.java:156)
	at org.apache.wayang.core.platform.PushExecutorTemplate.execute(PushExecutorTemplate.java:61)
	at org.apache.wayang.core.platform.CrossPlatformExecutor.execute(CrossPlatformExecutor.java:378)
	at org.apache.wayang.core.platform.CrossPlatformExecutor.executeSingleStage(CrossPlatformExecutor.java:248)
	at org.apache.wayang.core.platform.CrossPlatformExecutor.runToBreakpoint(CrossPlatformExecutor.java:320)
	at org.apache.wayang.core.platform.CrossPlatformExecutor.executeUntilBreakpoint(CrossPlatformExecutor.java:156)
	at org.apache.wayang.core.api.Job.execute(Job.java:525)
	at org.apache.wayang.core.api.Job.doExecute(Job.java:309)
	at org.apache.wayang.core.util.OneTimeExecutable.tryExecute(OneTimeExecutable.java:41)
	at org.apache.wayang.core.util.OneTimeExecutable.execute(OneTimeExecutable.java:54)
	at org.apache.wayang.core.api.Job.execute(Job.java:244)
	at org.apache.wayang.core.api.WayangContext.execute(WayangContext.java:120)
	at org.apache.wayang.core.api.WayangContext.execute(WayangContext.java:108)
	at org.apache.wayang.api.PlanBuilder.buildAndExecute(PlanBuilder.scala:105)
	at org.apache.wayang.api.DataQuanta.collect(DataQuanta.scala:758)
	at org.apache.wayang.api.DataQuantaBuilder.collect(DataQuantaBuilder.scala:369)
	at org.apache.wayang.api.DataQuantaBuilder.collect$(DataQuantaBuilder.scala:367)
	at org.apache.wayang.api.BasicDataQuantaBuilder.collect(DataQuantaBuilder.scala:448)
	at org.apache.wayang.apps.wordcount.WordCount.main(WordCount.java:76)
Caused by: java.lang.IllegalArgumentException
	at org.apache.flink.shaded.asm5.org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.apache.flink.shaded.asm5.org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.apache.flink.shaded.asm5.org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.apache.flink.api.java.ClosureCleaner.getClassReader(ClosureCleaner.java:148)
	at org.apache.flink.api.java.ClosureCleaner.cleanThis0(ClosureCleaner.java:115)
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:75)
	at org.apache.flink.api.java.DataSet.clean(DataSet.java:186)
	at org.apache.flink.api.java.operators.UnsortedGrouping.reduce(UnsortedGrouping.java:147)
	at org.apache.wayang.flink.operators.FlinkReduceByOperator.evaluate(FlinkReduceByOperator.java:101)
	at org.apache.wayang.flink.execution.FlinkExecutor.execute(FlinkExecutor.java:104)
	... 24 more

**Comment by paulk-asert** [comment]
ASM ClassReader often fails when reading an unsupported JDK class version. Perhaps try using a different JDK version?

**Comment by zkaoudi** [comment]
Works now
