### ISSUE TITLE
FAILED UNIT TEST - Cloud based build is blocked

### ISSUE THREAD

**Issue by kamir** [apache/incubator-wayang#465]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.wayang.java.test.KafkaClientTest
> 0 ... 
*** [TOPIC-Name] banking-tx-small-csv ***
>   Read from topic ... 
> 1 ... 
null
null
null
null
null
null
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.04 s <<< FAILURE! - in org.apache.wayang.java.test.KafkaClientTest
Error:  org.apache.wayang.java.test.KafkaClientTest.testReadFromKafkaTopic  Time elapsed: 0.022 s  <<< ERROR!
java.lang.NullPointerException
	at org.apache.wayang.java.test.KafkaClientTest.getDefaultProperties(KafkaClientTest.java:113)
	at org.apache.wayang.java.test.KafkaClientTest.testReadFromKafkaTopic(KafkaClientTest.java:49)

[INFO] Running org.apache.wayang.java.execution.JavaExecutorTest
### 11 ... 

Error:    JavaKafkaTopicSourceTest.testReadFromKafkaTopic:94 » NullPointer

Error:    KafkaClientTest.testReadFromKafkaTopic:49->getDefaultProperties:113 » NullPointer

**Comment by kamir** [comment]
The tests have temporarily been deactivated.
